<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Rvvup\Payments\Block\Info $block
 */
/** Magento 2.3.5 backward compatibility fix */

use Rvvup\Payments\Gateway\Method;

if (!isset($escaper)) {
    $escaper = $block;
}
$specificInfo = $block->getSpecificInformation();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $escaper->escapeHtml($paymentTitle) ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value): ?>
            <tr>
                <th><?= $escaper->escapeHtml($label) ?>:</th>
                <td>
                    <?= /* @noEscape */ nl2br($escaper->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php if ($block->getAdditionalInformation(Method::DASHBOARD_URL)): ?>
        <tr>
            <th><?= $escaper->escapeHtml('Dashboard Link') ?>:</th>
            <td>
                <a href="<?= $escaper->escapeUrl($block->getAdditionalInformation(Method::DASHBOARD_URL)) ?>"
                   target="_blank">
                    <?= $escaper->escapeHtml($block->getAdditionalInformation(Method::ORDER_ID)) ?>
                </a>
            </td>
        </tr>
        <?php endif; ?>
    </table>
<?php endif;?>
