<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Rvvup\Payments\Block\Info $block
 */
/** Magento 2.3.5 backward compatibility fix */
if (!isset($escaper)) {
    $escaper = $block;
}
use Rvvup\Payments\Block\Info;

$specificInfo = $block->getSpecificInformation();
$paymentTitle = '';
$storeId = $block->getInfo()->getOrder()->getStoreId();
if ($block->getMethod()->getConfigData('title', $storeId) == 'Rvvup') {
    $paymentTitle = $block->getMethod()->getConfigData('title', $storeId);
}

$paymentMethodTitle = null;
?>

<?php if ($specificInfo): ?>
    <?php foreach ($specificInfo as $label => $value): ?>
        <?php if ($label === Info::LABEL_METHOD_TITLE): ?>
            <?php $paymentMethodTitle = implode(' ', $block->getValueAsArray($value, true)); ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif;?>
<br>
<?php if ($paymentTitle && $paymentMethodTitle): ?>
    <?= $escaper->escapeHtml($paymentTitle) . ' - ' . $escaper->escapeHtml($paymentMethodTitle) ?>
<?php else:?>
    <?php if ($paymentTitle): ?>
        <?= $escaper->escapeHtml($paymentTitle)?>
    <?php endif;?>

    <?php if ($paymentMethodTitle): ?>
        <?= $escaper->escapeHtml($paymentMethodTitle)?>
    <?php endif;?>
<?php endif; ?>
