<?php
/**
 * Load available assets on any template, currently used for PayPal only
 *
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
/** Magento 2.3.5 backward compatibility fix */
if (!isset($escaper)) {
    $escaper = $block;
}

/** @var \Rvvup\Payments\ViewModel\Assets $assetsViewModel */
$assetsViewModel = $block->getData('rvvup_payments_assets_view_model');

// Load specific payment methods if requested.
$paymentMethodsScriptAssets = $assetsViewModel !== null ? $assetsViewModel->getPaymentMethodsScriptAssets([]) : [];
?>
<?php foreach ($paymentMethodsScriptAssets as $method => $scripts): ?>
    <?php foreach ($scripts as $index => $script): ?>
        <?php // phpcs:disable Squiz.PHP.NonExecutableCode.Unreachable ?>
        <?php if (!is_array($script)): ?>
            <?php continue; ?>
        <?php endif; ?>
        <?php // phpcs:enable ?>
        <script id="<?= $escaper->escapeHtmlAttr($assetsViewModel->getScriptElementId($method, (string) $index)) ?>"
            <?php foreach ($assetsViewModel->getScriptDataAttributes($script) as $dataAttribute => $value): ?>
                <?php if ($value === null): ?>
                    <?= $escaper->escapeHtmlAttr($dataAttribute) ?>
                <?php else: ?>
                    <?= $escaper->escapeHtmlAttr($dataAttribute) . '="' . $escaper->escapeHtmlAttr($value) . '"' ?>
                <?php endif; ?>
            <?php endforeach; ?>
                src="<?= $escaper->escapeUrl($assetsViewModel->getScriptElementSrc($script)) ?>"></script>
    <?php endforeach; ?>
<?php endforeach; ?>
