<?php
/**
 * @var \Magento\Checkout\Block\Cart $block
 * @var \Rvvup\Payments\ViewModel\Clearpay $clearpay
 * @var \Magento\Framework\Escaper $escaper
 */
/** Magento 2.3.5 backward compatibility fix */
if (!isset($escaper)) {
    $escaper = $block;
}
$clearpay = $block->getClearpay();
?>
<?php if (!$block->hasError() && $clearpay->showByCart()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Rvvup_Payments/js/method/clearpay": {
                    "storeCode": "<?= /** @noEscape */ $clearpay->getStoreCode() ?>"
                }
            }
        }
    </script>
    <div class="clearpay">
        <afterpay-placement style="display:none" id="clearpay-summary"
            data-locale="<?= $escaper->escapeHtmlAttr($clearpay->getCurrentLocale()) ?>"
            data-currency="<?= $escaper->escapeHtmlAttr($clearpay->getCurrentCurrencyCode()) ?>"
            data-amount="<?= $escaper->escapeHtmlAttr($clearpay->getCartTotal()) ?>"
            data-logo-type="<?= $escaper->escapeHtmlAttr($clearpay->getLogoType()) ?>"
            data-badge-theme="<?= $escaper->escapeHtmlAttr($clearpay->getBadgeTheme()) ?>"
            data-modal-theme="<?= $escaper->escapeHtmlAttr($clearpay->getModalTheme()) ?>"
        ></afterpay-placement>
    </div>
<?php endif; ?>
