<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Rvvup\Payments\Block\Paypal $block
 * @var \Rvvup\Payments\ViewModel\PayPal $paypalViewModel
 */
$paypalViewModel = $block->getData('rvvup_payments_paypal_view_model');

if ($paypalViewModel === null ||
    $block->getQuote() === null ||
    !$paypalViewModel->isAvailable((string) $block->getQuote()->getGrandTotal())) {
    return;
}
$quoteId = $block->getMaskedQuoteId();
$container = $block->getNameInLayout() . '-container';
$querySelector = '.' . $container;
$isCartPage = $block->getData('is_cart_page');
$scope = $isCartPage ? 'cart' : 'miniCart';
?>

<div class="rvvup-paypal-express grow z-0">
    <div class="<?= $block->escapeHtml($block->getNameInLayout()) ?>-container" data-mage-init='{
        "rvvupPaypalScript":{
            "buttonQuerySelector":"<?= $block->escapeHtml($querySelector) ?>",
            "cartId": "<?= $block->escapeHtml($quoteId) ?>",
            "scope":"<?= $block->escapeHtml($scope) ?>"
            }
         }'>
    </div>
</div>
