<?php

declare(strict_types=1);

/**
 * @var \Rvvup\Payments\Block\Adminhtml\System\Config\Form\Field\AccountDashboardLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
/** Magento 2.3.5 backward compatibility fix */
if (!isset($escaper)) {
    $escaper = $block;
}

?>
<div class="buttons-container">
    <button id="<?= $escaper->escapeHtmlAttr($block->getData('id')) ?>"
            onclick="<?= $escaper->escapeHtmlAttr($block->getData('onclick')) ?>"
    ><?= $escaper->escapeHtml($block->getData('link_title')) ?></button>
</div>
