<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?=
/* @noEscape */ $secureRenderer->renderTag(
    'script',
    ['type' => 'text/x-magento-init'],
    '{
        "*": {
            "Rvvup_Payments/js/view/payment/messages": {}
        }
    }',
    false
);
?>
