<?php

if ($item = $block->getItem()):?>
    <table class="qty-table">
        <tr>
            <th><?= $block->escapeHtml(__('Ordered')); ?></th>
            <td><?= (int)$item->getQtyOrdered()?></td>
        </tr>

        <?php
        if ((int)$item->getQtyInvoiced()):?>
            <tr>
                <th><?= $block->escapeHtml(__('Invoiced')); ?></th>
                <td><?= (int)$item->getQtyInvoiced()?></td>
            </tr>
        <?php endif; ?>
        <?php
        if ((int)$item->getQtyShipped()):?>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped')); ?></th>
                <td><?= (int)$item->getQtyShipped()?></td>
            </tr>
        <?php endif; ?>
        <?php
        if ((int)$item->getQtyRefunded()):?>
            <tr>
                <th><?= $block->escapeHtml(__('Refunded')); ?></th>
                <td><?= (int)$item->getQtyRefunded()?></td>
            </tr>
        <?php endif; ?>
        <?php
        if ($block->getQtyRvvupPendingRefund($item)):?>
            <tr>
                <th><?= $block->escapeHtml(__('Pending refund from Rvvup')); ?></th>
                <td><?= $block->escapeHtml($block->getQtyRvvupPendingRefund($item))?></td>
            </tr>
        <?php endif; ?>
        <?php
        if ((int)$item->getQtyCanceled()):?>
            <tr>
                <th><?= $block->escapeHtml(__('Canceled')); ?></th>
                <td><?= (int)$item->getQtyCanceled()?></td>
            </tr>
        <?php endif; ?>
    </table>
<?php endif; ?>
