name: E2E Tests Workflow
on:
  pull_request:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
    inputs:
      rvvupPluginVersion:
        description: 'Rvvup Plugin Version'
        required: true
        default: 'dev-main'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  end-2-end-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - MAGENTO_VERSION: 2.4.7

    env:
      MAGENTO_VERSION: ${{ matrix.MAGENTO_VERSION }}
      RVVUP_PLUGIN_VERSION: ${{ github.event.inputs.rvvupPluginVersion || format('dev-{0}', github.head_ref || github.ref_name) }}
      MAGENTO_REPO_PUBLIC_KEY: ${{ secrets.REPO_PUB_KEY }}
      MAGENTO_REPO_PRIVATE_KEY: ${{ secrets.REPO_SEC_KEY }}
      RVVUP_API_KEY: ${{ secrets.RVVUP_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
